---

# Main tasks file for airflow role

- name: 'INIT | Manage variables to use for our target'
  import_tasks: "manage_variables.yml"
  tags:
    - 'role::airflow'
    - 'role::airflow::init'
    - 'role::airflow::install'


# Installation tasks management
- name: 'INSTALL | Include installation tasks'
  import_tasks: "manage_installation.yml"
  environment:
    AIRFLOW_HOME: "{{ airflow_application_home }}"
  become: true
  tags:
    - 'role::airflow'
    - 'role::airflow::install'

# Sqlite installation tasks management
- name: 'INSTALL | Include sqlite installation tasks'
  import_tasks: "manage_sqlite_install.yml"
  environment:
    - CFLAGS: -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_LOAD_EXTENSION -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_UPDATE_DELETE_LIMIT -DSQLITE_SOUNDEX -DSQLITE_TEMP_STORE=3 -DSQLITE_USE_URI -O2 -fPIC
    - PREFIX: /usr/local
    - LIBS: "-lm"
  become: true
  tags:
    - 'role::airflow'
    - 'role::airflow::config'

# Configuration tasks management
- name: 'CONFIG | Include configuration tasks'
  import_tasks: "manage_configuration.yml"
  environment:
    AIRFLOW_HOME: "{{ airflow_application_home }}"
    LD_LIBRARY_PATH: "/usr/local/lib:$LD_LIBRARY_PATH"
  become: true
  tags:
    - 'role::airflow'
    - 'role::airflow::config'


# Services tasks management
- name: 'SERVICE | Include services configuration tasks'
  import_tasks: "manage_services.yml"
  become: true
  tags:
    - 'role::airflow'
    - 'role::airflow::config'
    - 'role::airflow::install'


# Connections tasks management
- name: 'CONFIG | Include connections tasks'
  import_tasks: "manage_connections.yml"
  environment:
    AIRFLOW_HOME: "{{ airflow_application_home }}"
    LD_LIBRARY_PATH: "/usr/local/lib:$LD_LIBRARY_PATH"
  become: true
  tags:
    - 'role::airflow'
    - 'role::airflow::config'


# Airflow variables tasks management
- name: 'CONFIG | Include variables tasks'
  import_tasks: "manage_airflow_variables.yml"
  environment:
    AIRFLOW_HOME: "{{ airflow_application_home }}"
    LD_LIBRARY_PATH: "/usr/local/lib:$LD_LIBRARY_PATH"
  become: true
  tags:
    - 'role::airflow'
    - 'role::airflow::config'

# Airflow DAGs tasks management
- name: 'CONFIG | Include DAG codebases'
  import_tasks: "manage_dags.yml"
  environment:
    AIRFLOW_HOME: "{{ airflow_application_home }}"
    LD_LIBRARY_PATH: "/usr/local/lib:$LD_LIBRARY_PATH"
  become: true
  tags:
    - 'role::airflow'
    - 'role::airflow::config'
    - 'role::airflow::dags'
