---

# Build dictionary in Airflow import format
- name: "CONFIG | CONNECTIONS | Build import structure"
  ansible.builtin.set_fact:
    airflow_connections_import: >-
      {{
        airflow_connections_import | default({}) |
        combine({
          item.conn_id: {
            "conn_type": (item.conn_uri | urlsplit).scheme,
            "host": (item.conn_uri | urlsplit).hostname,
            "port": (item.conn_uri | urlsplit).port,
            "extra": (item.conn_extra | default({}) | to_json)
          }
        })
      }}
  loop: "{{ airflow_connections }}"
  when:
    - airflow_connections | default([]) | length > 0
    - (item.conn_uri | default("")) | length > 0
  tags:
    - connections


# Write JSON file used by airflow connections import
- name: "CONFIG | CONNECTIONS | Write connections import file"
  become_user: "{{ airflow_user_name }}"
  become: true
  ansible.builtin.copy:
    dest: /tmp/airflow_connections.json
    content: "{{ airflow_connections_import | to_json }}"
    mode: "0600"
  when: airflow_connections | default([]) | length > 0
  tags:
    - connections


# Import connections (overwrite existing ones)
- name: "CONFIG | CONNECTIONS | Import connections"
  become_user: "{{ airflow_user_name }}"
  become: true
  ansible.builtin.command:
    argv:
      - "{{ airflow_virtualenv }}/bin/airflow"
      - connections
      - import
      - "--overwrite"
      - /tmp/airflow_connections.json
  changed_when: false
  environment:
    AIRFLOW__METRICS__STATSD_ON: "False"
  when: airflow_connections | default([]) | length > 0
  tags:
    - connections