---

- name: Converge
  hosts: all
  roles:
    - role: ansible-role-airflow
      dags_git_repositories:
        - repo: "https://github.com/tulibraries/cob_datapipeline.git"
          dest_folder: "cob_datapipeline"
          branch_or_release: "main"
        - repo: "https://github.com/tulibraries/funcake_dags.git"
          dest_folder: "funcake_dags"
          branch_or_release: ""
      airflow_extra_packages:
        - name: 'apache-airflow[amazon]'
        - name: 'werkzeug'
  vars:
    airflow_fernet_key: '46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho='
    python_version: '3.9.10'
