---
scenario:
  name: default
  test_sequence:
    - cleanup
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
dependency:
  name: galaxy
  role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: rockylinux
    image: geerlingguy/docker-rockylinux9-ansible:latest
    command: /sbin/init
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
verifier:
  name: testinfra
