---

- name: Prepare
  hosts: all
  pre_tasks:
    - name: Install sshd
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - openssh
        - openssh-server
        - openssh-clients
        - openssl-libs
    - name: start the sshd
      service:
        name: sshd
        state: started
  roles:
    - role: tulibraries.server-bootstrap
